language: swift

osx_image: xcode7.3

before_script:
    - cd Travis
script:
    - travis_wait 60 ./Travis/Test.sh

after_success:
    - Successful completion!

branches:
    only:
        - master
install:
    - travis_wait 20 pod install

notifications:
    email:
        recipients:
            - aynur.galiev@flatstack.com
    on_success: always
    on_failure: always