language: swift

osx_image: xcode7.3

before_script:
    - cd Travis
    - chmod +x Travis/Test.sh

script:
 - travis_wait 10 Travis/Test.sh

after_success:
    - Successful completion!

branches:
    only:
        - master

notifications:
    email:
        recipients:
            - aynur.galiev@flatstack.com
    on_success: always
    on_failure: always